name: ezplotly_env
channels:
  - defaults
dependencies:
  - pip:
    - plotly
    - numpy
    - scipy
    - pandas
    - scikit-learn
    - kaleido
    - jupyter
    - nose
    - 'black[jupyter]'
    - twine